name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it support?
      placeholder: As a roadway survey planner, I need to optimize routes with time windows because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Describe the desired behavior.
      placeholder: |
        Add a `time_windows` parameter to the pipeline that accepts:
        - Start time for each segment
        - End time for each segment
        - Route should respect these constraints...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches or solutions did you consider?
      placeholder: |
        - Using external scheduling tool (but integration is difficult)
        - Manual route splitting (but not scalable)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your use case?
      options:
        - Critical - Blocking my work
        - High - Important but have workaround
        - Medium - Would be nice to have
        - Low - Future enhancement
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which component does this feature affect?
      options:
        - Core routing algorithms
        - Visualization
        - KML parsing
        - Performance optimization
        - API/Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you would use this feature (code examples, API calls, etc.)
      placeholder: |
        ```python
        pipeline.run(
            kml_file='survey.kml',
            algorithm='v4',
            time_windows={
                'seg_001': (datetime(2025, 1, 1, 9, 0), datetime(2025, 1, 1, 17, 0)),
                ...
            }
        )
        ```
      render: python

  - type: textarea
    id: impact
    attributes:
      label: Performance Impact
      description: Will this affect performance for large datasets? Any memory/speed considerations?
      placeholder: May require additional constraint checking during routing, but shouldn't significantly impact performance

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, references, or links related to this feature
      placeholder: |
        - Similar feature in other routing libraries
        - Academic papers on time-constrained routing
        - Real-world dataset characteristics

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals (DRPP optimization)
          required: true
        - label: I have considered backward compatibility
          required: false
